### ISSUE TITLE
Fork Deez Nuts

### ISSUE THREAD

**Issue by Stormalisk** [anihacc/Ultimacraft-project-public-notice#11]
Is there any plans for any pre 1.7.10 mods or all foreign or defunct mods as well?

**Comment by mothmoss** [comment]
please port industrial craft beta 1.3 i would really like that i think it would go well with IC2

**Comment by anihacc** [comment]
> please port industrial craft beta 1.3 i would really like that i think it would go well with IC2

provide links to such mods and if they are not ARR, I shall

**Comment by IncandescenceSy** [comment]
oh and you cant forget gregtech 6 unnoficicial and dream craft

**Comment by anihacc** [comment]
> oh and you cant forget gregtech 6 unnoficicial and dream craft

Greg, yes, dream... DREAM?! oh- I'll consider that.
