### ISSUE TITLE
When will this be ready?

### ISSUE THREAD

**Issue by IamRyan30** [anihacc/Ultimacraft-project-public-notice#13]
title

**Comment by CodexAdrian** [comment]
[ _ ][ _ ][ _ ]
[ _ ][ X ][ _ ]
[ _ ][ _ ][ O ]

**Comment by IamRyan30** [comment]
[ _ ][ _ ][ X ]
[ _ ][ X ][ _ ]
[ _ ][ _ ][ O ]

**Comment by LHMezentierB** [comment]
[ _ ][ _ ][ X ]
[ _ ][ X ][ _ ]
[ O ][ _ ][ O ]

**Comment by IamRyan30** [comment]
[ _ ][ _ ][ X ]
[ _ ][ X ][ _ ]
[ O ][ X ][ O ]

**Comment by CodexAdrian** [comment]
[ _ ][ O ][ X ]
[ _ ][ X ][ _ ]
[ O ][ X ][ O ]

**Comment by IamRyan30** [comment]
[ _ ][ O ][ X ]
[ _ ][ X ][ X ]
[ O ][ X ][ O ]

**Comment by LHMezentierB** [comment]
[ _ ][ O ][ X ]
[ O ][ X ][ _ ]
[ O ][ X ][ O ]

**Comment by IamRyan30** [comment]
[ _ ][ O ][ X ]
[ O ][ X ][ _ ]
[ O ][ X ][ O ]
       [ X ]

**Comment by LHMezentierB** [comment]
That's _cheating!****_

**Comment by IamRyan30** [comment]
But you ignored my move :(
Oki, let's return to this point:
[ _ ][ O ][ X ]
[ _ ][ X ][ X ]
[ O ][ X ][ O ]

**Comment by LHMezentierB** [comment]
[ _ ][ O ][ X ]
[ O ][ X ][ X ]
[ O ][ X ][ O ]

**Comment by IamRyan30** [comment]
[ X ][ O ][ X ]
[ O ][ X ][ X ]
[ O ][ X ][ O ]

It is my honor to announce that nobody wins this round. We all shall meet again some day, and try again. Thank you all for your hard work, dedication and patience. Your efforts will never be forgotten.

**Comment by RPMYT** [comment]
[ X ] [ _ ] [ _ ]
[ _ ] [ _ ] [ _ ]
[ _ ] [ _ ] [ _ ]

**Comment by anihacc** [comment]
Who knows? Probably 3-10 years. Anyways, Imma leave this open. Keep playing your tic-tac-toe

**Comment by IamRyan30** [comment]
Oki, thank you

**Comment by DerCommander323** [comment]
[ X ] [ _ ] [ _ ]
[ _ ] [ O] [ _ ]
[ _ ] [ _ ] [ X ]

**Comment by IamRyan30** [comment]
[ X ] [ _ ] [ _ ]
[ _ ] [O] [ _ ]
[O] [ _ ] [ X ]

**Comment by BelgianSalamander** [comment]
[ X ] [ _ ] [ X ]
[ _ ] [O] [ _ ]
[O] [ _ ] [ X ]

**Comment by IamRyan30** [comment]
[ X ] [ _ ] [ X ]
[ _ ] [O] [O]
[O] [ _ ] [ X ]

**Comment by ProbablyNotPetey** [comment]
[ X ] [ X ] [ X ]
[ _ ] [ O ] [ O ]
[ O ] [ _ ] [ X ]

gg

**Comment by BelgianSalamander** [comment]
[ _ ] [ _ ] [ _ ]
[ _ ] [ X ] [ _ ]
[ _ ] [ _ ] [ _ ]

**Comment by IamRyan30** [comment]
_ ] [ _ ] [ O ]
[ _ ] [ X ] [ _ ]
[ _ ] [ _ ] [ _ ]

**Comment by BelgianSalamander** [comment]
[ _ ] [ _ ] [ O ]
[ X ] [ X ] [ _ ]
[ _ ] [ _ ] [ _ ]

**Comment by IamRyan30** [comment]
[ _ ] [ _ ] [ O ]
[ X ] [ X ] [ O ]
[ _ ] [ _ ] [ _ ]

**Comment by Ringlings** [comment]
I feel like this'll end in a draw

**Comment by anihacc** [comment]
no one continues the tic-tac-toe

**Comment by AutumnalModding** [comment]
> no one continues the tic-tac-toe

[ _ ] [ _ ] [ O ]
[ X ] [ X ] [ O ]
[ _ ] [ _ ] [ _ ]

**Comment by SmileycorpMC** [comment]
[ _ ] [ _ ] [ O ]
[ X ] [ X ] [ O ]
[ _ ] [ _ ] [ X ]
