### ISSUE TITLE
*sips drink*

### ISSUE THREAD

**Issue by CDAGaming** [anihacc/Ultimacraft-project-public-notice#14]
So, how's everyone's day?

_Also is CraftPresence just not cool enough to be forked, me sad, me not popular /s_

**Comment by amoooooo** [comment]
ikr! where's loot beams??

**Comment by ladylexxie** [comment]
Funny how things like KubeJS and Almost Unified got forked.
*you know... mods that help with mod unification...*

**Comment by amoooooo** [comment]
dont bother, not allowing loot beams to be ported to fabric because player is a vile person.

**Comment by anihacc** [comment]
sadge
