### ISSUE TITLE
Thoughts and notes 

### ISSUE THREAD

**Issue by MattiDragon** [anihacc/Ultimacraft-project-public-notice#16]
I don't see the benefit of doing this. It won't make compatability better, it'll be a huge amount of work in porting everything (and you don't even intend on publishing it apparently). I also don't understand the idea of forking a ~~bunch~~ ton of mods just to then go over and delete all forks you can't use.

If you made this a modpack you'd have several benefits:
 - You can use ARR mods that allow modpacks
 - You can get mod authors to fix their own mods instead of doing it yourself (I'm not gonna fix a bug in a fork that doesn't even have a good reason to exist)
 - The community might actually like your project instead of turning it into a meme
 - And probably a lot more

Btw have you ever ported a single larger mod? It can take months for a large team to do and you plan on doing major ports on hundreds of mods.

I also wonder about your method of choosing mods, you seem to have some duplicates and you didn't even consider the license to begin with (this whole thing is morally questionable, you need to at least stay legal).

I think you should instead help others improve: you said mods break each other too much, maybe go and PR some fixes, most devs will happily accept them. You complained about launchers, maybe make your own better one (or use anything else than curseforge). You could even port a few aboned projects if you want everything on the same version. Your time could be spent on so many more useful things than trying to merge 1.3k mods into one monstrosity.

**Comment by Decencies** [comment]
> Btw have you ever ported a single larger mod? It can take months for a large team to do and you plan on doing major ports on hundreds of mods.

Vouch for this.

Perhaps implementing https://github.com/Decencies/Articles/wiki/Lunar---Bridge would help.

(this must be a joke there is no way this man has enough time to do this)

**Comment by anihacc** [comment]
> > Btw have you ever ported a single larger mod? It can take months for a large team to do and you plan on doing major ports on hundreds of mods.
> 
> Vouch for this.
> 
> Perhaps implementing https://github.com/Decencies/Articles/wiki/Lunar---Bridge would help.
> 
> (this must be a joke there is no way this man has enough time to do this)

Oh I do have the time to do this, but I'll look into that link

**Comment by anihacc** [comment]
> I also wonder about your method of choosing mods, you seem to have some duplicates and you didn't even consider the license to begin with (this whole thing is morally questionable, you need to at least stay legal).

I have! I'm filtering AAR mods out

**Comment by anihacc** [comment]
> If you made this a modpack you'd have several benefits:
> 
>     * You can use ARR mods that allow modpacks
That would be nice, but the whole reason I'm making this is because I've had issues with a mod pack
>     * You can get mod authors to fix their own mods instead of doing it yourself (I'm not gonna fix a bug in a fork that doesn't even have a good reason to exist)
I'm not fixing it for them, I'm fixing it for me.
>     * The community might actually like your project instead of turning it into a meme
Don't care if it's a meme. MEME AWAY!
>     * And probably a lot more
List them and I'll think on them

**Comment by anihacc** [comment]
> Perhaps implementing https://github.com/Decencies/Articles/wiki/Lunar---Bridge would help.

YESSS! THIS LINK IS BEAUTIFUL! I SHALL USE IT! THANK YOU FOR GIVING DOBBY A LINK!
