### ISSUE TITLE
Unlicensed projects are treated as ARR by law in most places.

### ISSUE THREAD

**Issue by amoooooo** [anihacc/Ultimacraft-project-public-notice#2]
By not obeying this you are literally breaking the law, and can be charged.

**Comment by QinomeD** [comment]
> can be charged

thousand times

**Comment by anihacc** [comment]
What do you mean unlicensed?

**Comment by QinomeD** [comment]
Unlicensed means no (valid) license provided.

**Comment by anihacc** [comment]
Good to know, I'll get those removed. Thank you!

**Comment by amoooooo** [comment]
By the way, this includes mods who do not explicitly have a license file somewhere on their repo. As far as GitHub is concerned, repos without a license are ARR
