### ISSUE TITLE
Do you fully understand how much of a nightmare this is and will be?

### ISSUE THREAD

**Issue by ProbablyNotPetey** [anihacc/Ultimacraft-project-public-notice#29]
Like, I see the idea, but maintaining 1.3 thousand mods is not going to remove incompatibilities, it's just going to lead to worse performance for existing mods. And porting mods from anything older than 1.16 is going to require effectively an entire rewrite, or porting anything from forge to fabric. Not only that but quite a few of these mods are under licenses that are incompatible with other mods' licenses, and some are ARR.

Curious, have you actually ever made a mod? Or even programmed in Java? If the answer is no to either of these you're wasting your time.

**Comment by anihacc** [comment]
I have not actually made a mod, but this won't be a waste of time as it's an opportunity to learn. Also, I know.

**Comment by Ringlings** [comment]
This is not how you learn to mod, this is how you learn to sacrifice your sanity and all you hold dear to a satanic force beyond your control :catstare:
My point is, stop trying. If you’ve never modded before than it’s my humble opinion that you’re not going to get anywhere. Not to mention how easy it is to get into legal trouble (and how close you’re flying to the sun already on that front)
