### ISSUE TITLE
Performance expectations

### ISSUE THREAD

**Issue by FnigePython** [anihacc/Ultimacraft-project-public-notice#31]
Hey uhhh, what is the expected performance of this jar? (I this this is too big to be called a jar but I cant think of any alternative names)

**Comment by Ringlings** [comment]
I have an alternative name: abomination

**Comment by anihacc** [comment]
> I have an alternative name: abomination

I shall consider it, as it also fits as an accurate description

**Comment by anihacc** [comment]
> Hey uhhh, what is the expected performance of this jar? (I this this is too big to be called a jar but I cant think of any alternative names)

If you can run all the mods, you MIGHT be able to run this (???) I'm not entirely sure
