### ISSUE TITLE
RMM More Axolotl Variants Mod & More Axolotl Variants Mod API projects

### ISSUE THREAD

**Issue by AkashiiKun** [anihacc/Ultimacraft-project-public-notice#33]
More Axolotl Variants Mod is under ARR.
More Axolotl Variants API is under Apache version 2.0.

I do not allow you to add my projects into your all in one jar.

**Comment by anihacc** [comment]
Could you please link me to the mods or the branches to expedite the process?

**Comment by AkashiiKun** [comment]
https://github.com/anihacc/MoreAxolotlVariantsMod-Common

Checked you didn't fork the API but More Axolotl Variants Mod requires it.

**Comment by AkashiiKun** [comment]
> just don't use arr lmao problem solved

I use ARR because i want to. I don't want my project in a random project without asking for permission.

**Comment by anihacc** [comment]
I’m not gonna force any author to use any specific license just so I can
make my mod. If someone chooses to use ARR or no license (same thing
apparently) they chose to do that for a reason. I’m solving the problem of
ARR by removing those mods when I have some time.

**Comment by anihacc** [comment]
forgot that I removed this mod already
