### ISSUE TITLE
RMM Grass Overhaul, Boat Break Fix

### ISSUE THREAD

**Issue by nvb-uy** [anihacc/Ultimacraft-project-public-notice#34]
They're ARR.

This is probably a joke, but in the crazy case it isn't, I don't support this "project" which wouldn't make sense to make. And I don't want my mods to be inside this conceptual abomination. Just make a modpack, and use less mods, there's no way you're running 1300 mods at the same time.

**Comment by anihacc** [comment]
Can you provide a link to them?

**Comment by anihacc** [comment]
ok, I've found grass overhaul, but boat break fix's original repository seems to be missing. I did read your custom license and found that I require your explicit permission for publicly distributed modifications to your code. I'll go ahead and delete it
