### ISSUE TITLE
another issue cause they keep getting locked for ~mysterious reasons~

### ISSUE THREAD

**Issue by quat1024** [anihacc/Ultimacraft-project-public-notice#7]
Forgive modders for being annoyed but you basically did a github `@everyone`  !

> So, I had this experience with a modpack where the list said that some mods could be updated, so I did, and then everything broke. Then I read the page that said to use the in-Minecraft updater. I did, and it all broke again.

I'm going to assume you're referring to the CurseForge launcher modlist? Yeah, it's kind of a bummer that it loudly states "this mod is outdated! update it!" to *end users*. Choosing to take an update or not is the responsibility of the *packmaker*, not the end user - carefully reviewing changelogs, taking backups, testing things out... Intentionally using an outdated version is always an option.

Like, mods add and remove things in updates, that's why updates are made in the first place. There was one update to Botania that removed items called "mana petals" and replaced them with regular petals - of *course*, if you play a modpack with a bunch of custom Minetweaker scripts and update Botania past that version, the MineTweaker scripts would break. Duh.

The fix to this is easy: no one is forcing you to update anything. Don't update if you don't want to. Maybe discuss with launcher folks about toning down the urgency of those mod update notifications.

Making an entire spaghetti 1300-forks giant-jar funfair is a pretty heavy-handed solution to.. not clicking a button, which is very easy imo

(Additionally there is no "in-Minecraft updater", that was added by a mod and they will have the same problems)

> In addition, both in Minecraft and other games I play with mods, some just refuse to work with each other because their code doesn't mesh well.

If there is an incompatibility *report it to the mod authors*. Open an issue on Mod A's github that says "hey, its crashing when i do this with mod b installed" and *let us fix it*. I want to *know* about this stuff so i can fix it for *everyone*.

Minecraft is a bit unique compared to certain other games' modding communities because we try to make things Just Work out of the box, we don't require users to configure a "load order", etc. I don't have time to test my mod with every combination of every mod ever released so if somethings not working i wanna know!!

If a mod is abandonware, *then* it makes sense to make your own fork, or make a patcher mod (like good ol `BinniePatcher`)

> to prevent that, and to play all the cool mods at once without switching between versions, I'm combining it all into a single .jar file

What is the benefit of the "single jar file"? Mod incompatibilities don't arise because the code happens to be in two files. When incompat issues do arise, copy-pasting the source code of mod X into mod Y isn't going to magically fix them.

I'm simplifying a bit here but Java already doesn't care which jar a particular class comes from.

> for 1.19 fabric.

I think you are underestimating how hard it is to port a mod across versions and especially across loaders

**Comment by ProbablyNotPetey** [comment]
I feel like this project will be abandoned in like a month due to the sheer amount of work this would require. Also, seems like a horrible idea to force users to use 1.3 thousand mods at the same time.

**Comment by RPMYT** [comment]
I did have a talk with them on Discord, and it seems they're going to:
- filter out ARR mods
- split up JARs so it doesn't become a (and I quote) 200GB file
- not build a single jar for six months every time they make a typo
(also that 1.3k number is without ARR filtering)

**Comment by IMS212** [comment]
Agree with quat here; I also did not consent to my mods (Iris, Sodium, etc) being used. If you continue with this, please get direct consent from all 1300 devs. This is the equivalent of making a client without asking the mod devs for the mods.

**Comment by ladylexxie** [comment]
> I feel like this project will be abandoned in like a month due to the sheer amount of work this would require. Also, seems like a horrible idea to force users to use 1.3 thousand mods at the same time.

I was actually feeling more like a week at best lol

**Comment by Officialy** [comment]
They'd need to upgrade their ram 6 times to even build the project

**Comment by RogueLogix** [comment]
> Forgive modders for being annoyed but you basically did a github `@everyone` !

you should have seen when [someone pinged everyone in the Epic Games org](https://github.com/EpicGames/Signup/pull/24), pinged about 400k people

**Comment by anihacc** [comment]
> 

I remember hearing about that. That was interesting

**Comment by anihacc** [comment]
> > Forgive modders for being annoyed but you basically did a github `@everyone` !
> 
> you should have seen when [someone pinged everyone in the Epic Games org](https://github.com/EpicGames/Signup/pull/24), pinged about 400k people



> I feel like this project will be abandoned in like a month due to the sheer amount of work this would require. Also, seems like a horrible idea to force users to use 1.3 thousand mods at the same time.

I started thinking this up about a year ago. just didn't know where to start. I will never abandon it.

**Comment by anihacc** [comment]
> Agree with quat here; I also did not consent to my mods (Iris, Sodium, etc) being used. If you continue with this, please get direct consent from all 1300 devs. This is the equivalent of making a client without asking the mod devs for the mods.

If you have an issue, either contact me on discord or open up an issue with the RMM tag and link me to your mod or the forks.

**Comment by anihacc** [comment]
> Forgive modders for being annoyed but you basically did a github `@everyone` !
> 
> > So, I had this experience with a modpack where the list said that some mods could be updated, so I did, and then everything broke. Then I read the page that said to use the in-Minecraft updater. I did, and it all broke again.
> 
> I'm going to assume you're referring to the CurseForge launcher modlist? Yeah, it's kind of a bummer that it loudly states "this mod is outdated! update it!" to _end users_. Choosing to take an update or not is the responsibility of the _packmaker_, not the end user - carefully reviewing changelogs, taking backups, testing things out... Intentionally using an outdated version is always an option.
> 
> Like, mods add and remove things in updates, that's why updates are made in the first place. There was one update to Botania that removed items called "mana petals" and replaced them with regular petals - of _course_, if you play a modpack with a bunch of custom Minetweaker scripts and update Botania past that version, the MineTweaker scripts would break. Duh.
> 
> The fix to this is easy: no one is forcing you to update anything. Don't update if you don't want to. Maybe discuss with launcher folks about toning down the urgency of those mod update notifications.
> 
> Making an entire spaghetti 1300-forks giant-jar funfair is a pretty heavy-handed solution to.. not clicking a button, which is very easy imo

Coders spend months to make a five minute task simpler. I'm going to spend 50 years!

**Comment by anihacc** [comment]
> (Additionally there is no "in-Minecraft updater", that was added by a mod and they will have the same problems)

That's exactly what I was talking about.

**Comment by anihacc** [comment]
Also, I locked the issues to keep them open and pin them to make them more noticeable, so people would actually read them.

**Comment by Bluexin** [comment]
> Agree with quat here; I also did not consent to my mods (Iris, Sodium, etc) being used. If you continue with this, please get direct consent from all 1300 devs. This is the equivalent of making a client without asking the mod devs for the mods.

@IMS212 While I don't think this project will go anywhere due to the massive amount of work that would be required (nor do I think this project is a good idea), I'd like to correct you on one thing. You _did_, in fact, consent to your mods being used. Idk about your other mods, but according to your repos Iris & Sodium are licensed under GNU LGPL 3.0, which you might want to review if you don't actually agree with them. Note that the effect won't be retroactive, meaning already released versions of both will still be licensed under LGPL 3.0 even if you were to change license moving forward.
