### ISSUE TITLE
Modpacks are a thing.

### ISSUE THREAD

**Issue by Saereth** [anihacc/Ultimacraft-project-public-notice#8]
What you want is a mod pack not a mod. If you want to fork 1.3k mods and reuse as much as code as possible in a library then have at it but it's a tremendous waste of your time. You can accomplish the same thing in a mod pack from an end users perspective. 

You are still going to have to track down issues and fix them so you might as well contribute to the original author.

If not, pick the mods you actually want, design a pack and go from there. Even as a pack designer I couldn't pick it 1.3k mods that I'd include in any pack, you can usually cover all your features in less than a few hundred, more is not always better and often worse for compatibility.
Looking at the date quickly approaching April first I'm hoping this is a weird joke attempt.

**Comment by ladylexxie** [comment]
![1dbc12f41ea990aadd93b41d624017fa6a8b4fae](https://user-images.githubusercontent.com/30494658/225757435-a9fd7ebb-887b-498a-bcf8-0c96d5204f47.jpeg)

**Comment by amoooooo** [comment]
I love people who know what they're doing!

**Comment by anihacc** [comment]
> What you want is a mod pack not a mod. If you want to fork 1.3k mods and reuse as much as code as possible in a library then have at it but it's a tremendous waste of your time. You can accomplish the same thing in a mod pack from an end users perspective.
> 
> You are still going to have to track down issues and fix them so you might as well contribute to the original author.

you can't link mods over multiple versions into your pack, now can you?

**Comment by anihacc** [comment]
> ![1dbc12f41ea990aadd93b41d624017fa6a8b4fae](https://user-images.githubusercontent.com/30494658/225757435-a9fd7ebb-887b-498a-bcf8-0c96d5204f47.jpeg)

NOPE!

**Comment by Ringlings** [comment]
> > What you want is a mod pack not a mod. If you want to fork 1.3k mods and reuse as much as code as possible in a library then have at it but it's a tremendous waste of your time. You can accomplish the same thing in a mod pack from an end users perspective.
> > You are still going to have to track down issues and fix them so you might as well contribute to the original author.
> 
> you can't link mods over multiple versions into your pack, now can you?

You can if you fork, port, and include them in the pack
